import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

const translations = {
  zh: {
    appName: '企微任务管家',
    dashboard: '仪表盘',
    taskList: '任务列表',
    teamStats: '团队统计',
    calendarManage: '日历日程',
    calendarManageTitle: '日历与日程管理',
    calendarManageDesc: '统一管理企业微信日历、日程与参与人。',
    settings: '系统设置',
    system: '系统管理',
    home: '首页',
    search: '全局搜索...',
    operationFailed: '操作失败，请稍后重试',
    syncNow: '立即同步',
    syncFailed: '同步失败，请稍后重试',
    syncRefreshFailed: '同步成功，但刷新任务列表失败，请稍后手动刷新',
    syncConfigMissing: '未配置同步日历，请联系管理员配置后重试',
    syncIpNotAllowed: '企微接口拒绝当前出口IP，请在应用可信IP中加入该IP后重试',
    loginWelcomeTitle: '欢迎使用任务管家',
    loginHintQr: '请使用企业微信扫码登录后继续。',
    loginHintOauth: '请在企业微信内完成授权登录后继续。',
    loginButtonQr: '企业微信扫码登录',
    loginButtonOauth: '企业微信授权登录',
    loginScanTitle: '扫码登录',
    loginScanSubtitle: '请使用企业微信扫描下方二维码完成登录。',
    loginScanRefreshing: '二维码跳转中，请稍候...',
    loginScanRetry: '刷新二维码',
    logout: '退出登录',

    overviewTitle: '概览',
    overviewSubtitle: '任务闭环与KPI实时监控。',
    totalTasks: '任务总数',
    completionRate: '完成率',
    waitingAcceptance: '待验收',
    overdueTasks: '逾期任务',
    completedOnTime: '按时闭环率',
    tasksWaiting: '等待管理者验收',
    overdue24h: '逾期超过24小时',
    weeklyAnalytics: '周数据分析',
    recentActivity: '近期动态',
    viewAll: '查看全部',
    completed: '已完成',
    rejected: '已驳回',
    needsAction: '待处理',
    noRisk: '风险可控',
    kpiTotalTaskDesc: '全量任务（含历史）',
    dueSoonSuffix: '项临近截止',
    activityCompleted: '已完成任务',
    activityWaitingVerify: '提交了验收',
    activityPending: '正在执行任务',

    taskManagement: '任务管理',
    taskMgmtSubtitle: '管理、验收及追踪团队任务。',
    createTask: '新建任务',
    createTaskTitle: '创建任务',
    createTaskDesc: '填写任务信息后将同步创建工作日程，并自动通知执行人。',
    createTaskTitlePlaceholder: '请输入任务标题',
    createTaskDescPlaceholder: '请输入任务描述（可选）',
    executorIdInputPlaceholder: '或手动输入执行人用户ID（如 zhangsan）',
    confirmCreateTask: '确认创建',
    creatingTask: '创建中...',
    selectExecutor: '请选择执行人',
    allTasks: '全部任务',
    pending: '待执行',
    waitingVerify: '待验收',
    searchPlaceholder: '搜索任务...',
    noTasks: '未找到符合条件的任务。',
    due: '截止',
    redo: '重做',
    creator: '发起人',
    executor: '执行人',
    pass: '通过',
    reject: '驳回',
    markComplete: '标记完成',
    cancel: '取消',
    confirmReject: '确认驳回',
    rejectTitle: '驳回任务',
    rejectDesc: '请输入驳回理由，任务将返回给执行人并增加重做计数。',
    enterReason: '输入驳回理由...',
    dueSoonLabel: '24小时内到期',
    overdueLabel: '已逾期',
    rejectReasonLabel: '驳回原因',
    viewDetail: '查看详情',
    taskDetailSubtitle: '任务详情与处理记录',
    close: '关闭',
    startTime: '开始时间',
    endTime: '截止时间',
    prevPage: '上一页',
    nextPage: '下一页',
    pageLabel: '第 {page} / {totalPages} 页',
    pageItems: '页',
    taskPaginationSummary: '显示 {start}-{end} 条，共 {total} 条',

    status_PENDING: '待执行',
    status_WAITING_VERIFY: '待验收',
    status_COMPLETED: '已闭环',
    status_REJECTED: '已驳回',

    teamStatsTitle: '团队统计看板',
    teamStatsDesc: '基于平台管理员与成员权限，查看成员和岗位统计表现。',
    teamMemberCount: '团队成员数',
    teamAvgCompletionRate: '平均完成率',
    teamOverdueCount: '团队逾期数',
    teamMemberBoard: '成员任务表现',
    teamTableTip: '基于当前任务实时统计',
    teamManagerRoleLabel: '管理员',
    teamExecutorRoleLabel: '成员',
    teamManagerBoard: '管理员看板',
    teamExecutorBoard: '成员看板',
    teamManagerPositionBoard: '管理员岗位分布',
    teamExecutorPositionBoard: '成员岗位分布',
    teamPosition: '岗位',
    teamTaskLoad: '任务量',
    teamDueSoonCount: '临近到期',
    teamOnTimeRate: '按时率',
    teamManagerTaskCount: '管理任务',
    teamExecutorTaskCount: '执行任务',
    teamNoStats: '暂无统计数据',
    teamStatsLoadFailed: '团队统计加载失败，请稍后重试。',
    teamActionHintTitle: '管理建议',
    teamActionHint1: '优先跟进“待验收”积压较高的成员，减少闭环延迟。',
    teamActionHint2: '对逾期任务较多成员安排复盘，优化执行节奏。',

    settingsTitle: '系统设置',
    settingsDesc: '管理提醒策略、同步操作与显示偏好。',
    settingsNotification: '提醒配置',
    settingsTaskReminderToggle: '开启任务提醒',
    settingsAutoSyncToggle: '开启自动同步标记',
    settingsDisplay: '显示配置',
    settingsLanguage: '首选语言',
    settingsOperations: '运维操作',
    settingsManualSync: '手动触发同步',
    saveSettings: '保存设置',
    saving: '保存中...',
    syncing: '同步中...',
    settingsSaved: '设置已保存。',
    settingsTaskSyncSuccess: '任务同步已触发。',
    systemUsersLoadFailed: '系统管理成员加载失败，请稍后重试。',
    systemContactPull: '拉取全量通讯录',
    systemContactPulling: '拉取中...',
    systemContactPullSuccess: '通讯录已刷新，共同步 {count} 个成员。',
    systemContactPullFailed: '通讯录刷新失败，请稍后重试。',
    systemRoleUpdateSuccess: '{name} 的平台角色已更新为 {role}。',
    systemRoleUpdateFailed: '更新平台角色失败，请稍后重试。',
    systemCurrentOperator: '当前操作人',
    systemAdminCount: '当前页管理员数',
    systemExecutorCount: '当前页成员数',
    systemAccessTitle: '平台权限与通讯录',
    systemAccessDesc: '基于本地通讯录快照按部门筛选成员，分配平台角色与管理员菜单权限，并查看个人日历绑定状态。',
    systemRoleManageEnabled: '你当前拥有超级管理员权限，可直接调整平台角色。',
    systemRoleManageReadonly: '当前账号为普通管理员，仅可查看角色分配结果。',
    systemAccessSearchPlaceholder: '搜索姓名、账号、岗位或日历名称',
    systemAccessRoleAll: '全部角色',
    systemAccessDepartmentFilterAll: '全部部门',
    systemAccessUser: '成员',
    systemAccessDepartment: '部门',
    systemAccessPosition: '岗位',
    systemAccessCalendar: '个人日历',
    systemAccessRole: '平台角色',
    systemAccessMenus: '菜单权限',
    systemAccessAction: '角色分配',
    systemUsersLoading: '正在加载通讯录与权限信息...',
    systemUsersEmpty: '当前没有可展示的成员数据，请先拉取通讯录。',
    systemRoleFixedHint: '超级管理员固定',
    systemDepartmentLoadFailed: '系统部门加载失败，请稍后重试。',
    systemMenuUpdateSuccess: '{name} 的菜单权限已更新。',
    systemMenuUpdateFailed: '更新菜单权限失败，请稍后重试。',
    systemAccessMenuSave: '保存菜单',
    systemAccessMenuSaving: '保存中...',
    systemAccessMenuReadonlyExecutor: '成员固定为任务列表与日历日程。',
    systemAccessMenuReadonlySuperAdmin: '超级管理员固定拥有全部菜单。',
    systemAccessMenuHintAdmin: '支持按管理员自定义可见菜单。',
    platformRoleSuperAdmin: '超级管理员',
    platformRoleAdmin: '管理员',
    platformRoleExecutor: '成员',

    teamAnalyticsComingSoon: '团队分析模块 (开发中)',
    settingsComingSoon: '系统设置模块 (开发中)',
  },
  en: {
    appName: 'WeCom Task Master',
    dashboard: 'Dashboard',
    taskList: 'Task List',
    teamStats: 'Team Stats',
    calendarManage: 'Calendar',
    calendarManageTitle: 'Calendar & Schedule Management',
    calendarManageDesc: 'Manage WeCom calendars, schedules, and attendees in one place.',
    settings: 'Settings',
    system: 'System',
    home: 'Home',
    search: 'Global search...',
    operationFailed: 'Operation failed, please retry later',
    syncNow: 'Sync Now',
    syncFailed: 'Sync failed, please retry later',
    syncRefreshFailed: 'Sync succeeded, but refreshing task list failed. Please reload later.',
    syncConfigMissing: 'Sync calendar is not configured. Please contact the administrator.',
    syncIpNotAllowed:
      'WeCom rejected the current outbound IP. Add this IP to the app trusted IP list and retry.',
    loginWelcomeTitle: 'Welcome to Task Bot',
    loginHintQr: 'Please scan with Enterprise WeChat to continue.',
    loginHintOauth: 'Please authorize in Enterprise WeChat to continue.',
    loginButtonQr: 'Login via WeCom QR',
    loginButtonOauth: 'Login via WeCom OAuth',
    loginScanTitle: 'Scan to Login',
    loginScanSubtitle: 'Use Enterprise WeChat to scan the QR code below.',
    loginScanRefreshing: 'Loading QR code...',
    loginScanRetry: 'Refresh QR Code',
    logout: 'Logout',

    overviewTitle: 'Overview',
    overviewSubtitle: 'Real-time task closed-loop and KPI monitoring.',
    totalTasks: 'Total Tasks',
    completionRate: 'Completion Rate',
    waitingAcceptance: 'Waiting Acceptance',
    overdueTasks: 'Overdue Tasks',
    completedOnTime: 'On-time close rate',
    tasksWaiting: 'Tasks waiting for manager verification',
    overdue24h: 'Overdue for over 24h',
    weeklyAnalytics: 'Weekly Analytics',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    completed: 'Completed',
    rejected: 'Rejected',
    needsAction: 'Needs Action',
    noRisk: 'Risk Controlled',
    kpiTotalTaskDesc: 'All tasks including history',
    dueSoonSuffix: ' nearing due',
    activityCompleted: 'completed task',
    activityWaitingVerify: 'submitted for verification',
    activityPending: 'is executing task',

    taskManagement: 'Task Management',
    taskMgmtSubtitle: 'Manage, verify and track team tasks.',
    createTask: 'Create Task',
    createTaskTitle: 'Create Task',
    createTaskDesc: 'Submitting will also create the linked work schedule and notify the assignee immediately.',
    createTaskTitlePlaceholder: 'Enter task title',
    createTaskDescPlaceholder: 'Enter task description (optional)',
    executorIdInputPlaceholder: 'Or input executor user ID manually (e.g. zhangsan)',
    confirmCreateTask: 'Create',
    creatingTask: 'Creating...',
    selectExecutor: 'Select assignee',
    allTasks: 'All Tasks',
    pending: 'Pending',
    waitingVerify: 'Waiting Verify',
    searchPlaceholder: 'Search tasks...',
    noTasks: 'No tasks found matching filters.',
    due: 'Due',
    redo: 'Redo',
    creator: 'Creator',
    executor: 'Executor',
    pass: 'Pass',
    reject: 'Reject',
    markComplete: 'Mark Complete',
    cancel: 'Cancel',
    confirmReject: 'Confirm Reject',
    rejectTitle: 'Reject Task',
    rejectDesc: 'Please provide a rejection reason. The task will be returned for rework.',
    enterReason: 'Enter rejection reason...',
    dueSoonLabel: 'Due within 24h',
    overdueLabel: 'Overdue',
    rejectReasonLabel: 'Reject Reason',
    viewDetail: 'View Detail',
    taskDetailSubtitle: 'Task detail and processing records',
    close: 'Close',
    startTime: 'Start Time',
    endTime: 'End Time',
    prevPage: 'Prev',
    nextPage: 'Next',
    pageLabel: 'Page {page} / {totalPages}',
    pageItems: 'page',
    taskPaginationSummary: 'Showing {start}-{end} of {total}',

    status_PENDING: 'Pending',
    status_WAITING_VERIFY: 'Waiting Verify',
    status_COMPLETED: 'Closed',
    status_REJECTED: 'Rejected',

    teamStatsTitle: 'Team Analytics',
    teamStatsDesc: 'View member and position performance based on admin and member permissions.',
    teamMemberCount: 'Team Members',
    teamAvgCompletionRate: 'Average Completion',
    teamOverdueCount: 'Team Overdue',
    teamMemberBoard: 'Member Performance',
    teamTableTip: 'Realtime stats based on current tasks',
    teamManagerRoleLabel: 'Admins',
    teamExecutorRoleLabel: 'Members',
    teamManagerBoard: 'Admin Board',
    teamExecutorBoard: 'Member Board',
    teamManagerPositionBoard: 'Admin Positions',
    teamExecutorPositionBoard: 'Member Positions',
    teamPosition: 'Position',
    teamTaskLoad: 'Task Load',
    teamDueSoonCount: 'Due Soon',
    teamOnTimeRate: 'On-time Rate',
    teamManagerTaskCount: 'Managed Tasks',
    teamExecutorTaskCount: 'Executed Tasks',
    teamNoStats: 'No statistics available.',
    teamStatsLoadFailed: 'Failed to load team statistics. Please retry later.',
    teamActionHintTitle: 'Management Suggestions',
    teamActionHint1: 'Prioritize members with high waiting-verify backlog to reduce close delays.',
    teamActionHint2: 'Review members with many overdue tasks to optimize execution rhythm.',

    settingsTitle: 'System Settings',
    settingsDesc: 'Manage reminder strategies, sync operations, and display preferences.',
    settingsNotification: 'Reminder Settings',
    settingsTaskReminderToggle: 'Enable task reminders',
    settingsAutoSyncToggle: 'Enable auto-sync flag',
    settingsDisplay: 'Display Settings',
    settingsLanguage: 'Preferred Language',
    settingsOperations: 'Operations',
    settingsManualSync: 'Trigger Manual Sync',
    saveSettings: 'Save Settings',
    saving: 'Saving...',
    syncing: 'Syncing...',
    settingsSaved: 'Settings saved.',
    settingsTaskSyncSuccess: 'Task sync has been triggered.',
    systemUsersLoadFailed: 'Failed to load system users.',
    systemContactPull: 'Pull Contacts',
    systemContactPulling: 'Pulling...',
    systemContactPullSuccess: 'Contact snapshot refreshed. Synced {count} users.',
    systemContactPullFailed: 'Failed to refresh contacts.',
    systemRoleUpdateSuccess: '{name} role updated to {role}.',
    systemRoleUpdateFailed: 'Failed to update platform role.',
    systemCurrentOperator: 'Current Operator',
    systemAdminCount: 'Admins On Page',
    systemExecutorCount: 'Members On Page',
    systemAccessTitle: 'Platform Access & Directory',
    systemAccessDesc: 'Filter members by department from the local contact snapshot, assign platform roles, and manage admin menu permissions.',
    systemRoleManageEnabled: 'You are a super admin and can update platform roles directly.',
    systemRoleManageReadonly: 'This account is a regular admin and can only view role assignments.',
    systemAccessSearchPlaceholder: 'Search by name, user ID, position, or calendar',
    systemAccessRoleAll: 'All Roles',
    systemAccessDepartmentFilterAll: 'All Departments',
    systemAccessUser: 'User',
    systemAccessDepartment: 'Department',
    systemAccessPosition: 'Position',
    systemAccessCalendar: 'Personal Calendar',
    systemAccessRole: 'Platform Role',
    systemAccessMenus: 'Menu Permissions',
    systemAccessAction: 'Role Assignment',
    systemUsersLoading: 'Loading directory and access data...',
    systemUsersEmpty: 'No users available. Pull contacts first.',
    systemRoleFixedHint: 'Super admin fixed',
    systemDepartmentLoadFailed: 'Failed to load departments.',
    systemMenuUpdateSuccess: '{name} menu permissions updated.',
    systemMenuUpdateFailed: 'Failed to update menu permissions.',
    systemAccessMenuSave: 'Save Menus',
    systemAccessMenuSaving: 'Saving...',
    systemAccessMenuReadonlyExecutor: 'Members are fixed to Task List and Calendar.',
    systemAccessMenuReadonlySuperAdmin: 'Super admins always keep the full menu set.',
    systemAccessMenuHintAdmin: 'Admin menus can be customized per user.',
    platformRoleSuperAdmin: 'Super Admin',
    platformRoleAdmin: 'Admin',
    platformRoleExecutor: 'Member',

    teamAnalyticsComingSoon: 'Team Analytics Module (Coming Soon)',
    settingsComingSoon: 'System Settings Module (Coming Soon)',
  }
};

type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
