import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

const translations = {
  zh: {
    appName: '企微任务管家',
    dashboard: '仪表盘',
    taskList: '任务列表',
    teamStats: '团队统计',
    settings: '系统设置',
    system: '系统管理',
    home: '首页',
    search: '全局搜索...',
    operationFailed: '操作失败，请稍后重试',
    syncNow: '立即同步',
    syncFailed: '同步失败，请稍后重试',
    loginWelcomeTitle: '欢迎使用任务管家',
    loginHintQr: '请使用企业微信扫码登录后继续。',
    loginHintOauth: '请在企业微信内完成授权登录后继续。',
    loginButtonQr: '企业微信扫码登录',
    loginButtonOauth: '企业微信授权登录',
    loginScanTitle: '扫码登录',
    loginScanSubtitle: '请使用企业微信扫描下方二维码完成登录。',
    loginScanRefreshing: '二维码跳转中，请稍候...',
    loginScanRetry: '刷新二维码',

    overviewTitle: '概览',
    overviewSubtitle: '任务闭环与KPI实时监控。',
    totalTasks: '任务总数',
    completionRate: '完成率',
    waitingAcceptance: '待验收',
    overdueTasks: '逾期任务',
    completedOnTime: '按时闭环率',
    tasksWaiting: '等待管理者验收',
    overdue24h: '逾期超过24小时',
    weeklyAnalytics: '周数据分析',
    recentActivity: '近期动态',
    viewAll: '查看全部',
    completed: '已完成',
    rejected: '已驳回',
    needsAction: '待处理',
    noRisk: '风险可控',
    kpiTotalTaskDesc: '全量任务（含历史）',
    dueSoonSuffix: '项临近截止',
    activityCompleted: '已完成任务',
    activityWaitingVerify: '提交了验收',
    activityPending: '正在执行任务',

    taskManagement: '任务管理',
    taskMgmtSubtitle: '管理、验收及追踪团队任务。',
    createTask: '新建任务',
    createTaskTitle: '创建任务',
    createTaskDesc: '填写任务信息后将自动通知执行人。',
    createTaskTitlePlaceholder: '请输入任务标题',
    createTaskDescPlaceholder: '请输入任务描述（可选）',
    executorIdInputPlaceholder: '或手动输入执行人用户ID（如 zhangsan）',
    confirmCreateTask: '确认创建',
    creatingTask: '创建中...',
    selectExecutor: '请选择执行人',
    allTasks: '全部任务',
    pending: '待执行',
    waitingVerify: '待验收',
    searchPlaceholder: '搜索任务...',
    noTasks: '未找到符合条件的任务。',
    due: '截止',
    redo: '重做',
    creator: '发起人',
    executor: '执行人',
    pass: '通过',
    reject: '驳回',
    markComplete: '标记完成',
    cancel: '取消',
    confirmReject: '确认驳回',
    rejectTitle: '驳回任务',
    rejectDesc: '请输入驳回理由，任务将返回给执行人并增加重做计数。',
    enterReason: '输入驳回理由...',
    dueSoonLabel: '24小时内到期',
    overdueLabel: '已逾期',
    rejectReasonLabel: '驳回原因',
    viewDetail: '查看详情',
    taskDetailSubtitle: '任务详情与处理记录',
    close: '关闭',
    startTime: '开始时间',
    endTime: '截止时间',

    status_PENDING: '待执行',
    status_WAITING_VERIFY: '待验收',
    status_COMPLETED: '已闭环',
    status_REJECTED: '已驳回',

    teamStatsTitle: '团队统计看板',
    teamStatsDesc: '按执行人维度查看任务负载、完成率与风险分布。',
    teamMemberCount: '团队成员数',
    teamAvgCompletionRate: '平均完成率',
    teamOverdueCount: '团队逾期数',
    teamMemberBoard: '成员任务表现',
    teamTableTip: '基于当前任务实时统计',
    teamActionHintTitle: '管理建议',
    teamActionHint1: '优先跟进“待验收”积压较高的成员，减少闭环延迟。',
    teamActionHint2: '对逾期任务较多成员安排复盘，优化执行节奏。',

    settingsTitle: '系统设置',
    settingsDesc: '管理提醒策略、同步操作与显示偏好。',
    settingsNotification: '提醒配置',
    settingsTaskReminderToggle: '开启任务提醒',
    settingsAutoSyncToggle: '开启自动同步标记',
    settingsDisplay: '显示配置',
    settingsLanguage: '首选语言',
    settingsOperations: '运维操作',
    settingsManualSync: '手动触发同步',
    saveSettings: '保存设置',
    saving: '保存中...',
    syncing: '同步中...',

    teamAnalyticsComingSoon: '团队分析模块 (开发中)',
    settingsComingSoon: '系统设置模块 (开发中)',
  },
  en: {
    appName: 'WeCom Task Master',
    dashboard: 'Dashboard',
    taskList: 'Task List',
    teamStats: 'Team Stats',
    settings: 'Settings',
    system: 'System',
    home: 'Home',
    search: 'Global search...',
    operationFailed: 'Operation failed, please retry later',
    syncNow: 'Sync Now',
    syncFailed: 'Sync failed, please retry later',
    loginWelcomeTitle: 'Welcome to Task Bot',
    loginHintQr: 'Please scan with Enterprise WeChat to continue.',
    loginHintOauth: 'Please authorize in Enterprise WeChat to continue.',
    loginButtonQr: 'Login via WeCom QR',
    loginButtonOauth: 'Login via WeCom OAuth',
    loginScanTitle: 'Scan to Login',
    loginScanSubtitle: 'Use Enterprise WeChat to scan the QR code below.',
    loginScanRefreshing: 'Loading QR code...',
    loginScanRetry: 'Refresh QR Code',

    overviewTitle: 'Overview',
    overviewSubtitle: 'Real-time task closed-loop and KPI monitoring.',
    totalTasks: 'Total Tasks',
    completionRate: 'Completion Rate',
    waitingAcceptance: 'Waiting Acceptance',
    overdueTasks: 'Overdue Tasks',
    completedOnTime: 'On-time close rate',
    tasksWaiting: 'Tasks waiting for manager verification',
    overdue24h: 'Overdue for over 24h',
    weeklyAnalytics: 'Weekly Analytics',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    completed: 'Completed',
    rejected: 'Rejected',
    needsAction: 'Needs Action',
    noRisk: 'Risk Controlled',
    kpiTotalTaskDesc: 'All tasks including history',
    dueSoonSuffix: ' nearing due',
    activityCompleted: 'completed task',
    activityWaitingVerify: 'submitted for verification',
    activityPending: 'is executing task',

    taskManagement: 'Task Management',
    taskMgmtSubtitle: 'Manage, verify and track team tasks.',
    createTask: 'Create Task',
    createTaskTitle: 'Create Task',
    createTaskDesc: 'After submission, the assignee receives a task card immediately.',
    createTaskTitlePlaceholder: 'Enter task title',
    createTaskDescPlaceholder: 'Enter task description (optional)',
    executorIdInputPlaceholder: 'Or input executor user ID manually (e.g. zhangsan)',
    confirmCreateTask: 'Create',
    creatingTask: 'Creating...',
    selectExecutor: 'Select assignee',
    allTasks: 'All Tasks',
    pending: 'Pending',
    waitingVerify: 'Waiting Verify',
    searchPlaceholder: 'Search tasks...',
    noTasks: 'No tasks found matching filters.',
    due: 'Due',
    redo: 'Redo',
    creator: 'Creator',
    executor: 'Executor',
    pass: 'Pass',
    reject: 'Reject',
    markComplete: 'Mark Complete',
    cancel: 'Cancel',
    confirmReject: 'Confirm Reject',
    rejectTitle: 'Reject Task',
    rejectDesc: 'Please provide a rejection reason. The task will be returned for rework.',
    enterReason: 'Enter rejection reason...',
    dueSoonLabel: 'Due within 24h',
    overdueLabel: 'Overdue',
    rejectReasonLabel: 'Reject Reason',
    viewDetail: 'View Detail',
    taskDetailSubtitle: 'Task detail and processing records',
    close: 'Close',
    startTime: 'Start Time',
    endTime: 'End Time',

    status_PENDING: 'Pending',
    status_WAITING_VERIFY: 'Waiting Verify',
    status_COMPLETED: 'Closed',
    status_REJECTED: 'Rejected',

    teamStatsTitle: 'Team Analytics',
    teamStatsDesc: 'View workload, completion rate, and risk distribution by assignee.',
    teamMemberCount: 'Team Members',
    teamAvgCompletionRate: 'Average Completion',
    teamOverdueCount: 'Team Overdue',
    teamMemberBoard: 'Member Performance',
    teamTableTip: 'Realtime stats based on current tasks',
    teamActionHintTitle: 'Management Suggestions',
    teamActionHint1: 'Prioritize members with high waiting-verify backlog to reduce close delays.',
    teamActionHint2: 'Review members with many overdue tasks to optimize execution rhythm.',

    settingsTitle: 'System Settings',
    settingsDesc: 'Manage reminder strategies, sync operations, and display preferences.',
    settingsNotification: 'Reminder Settings',
    settingsTaskReminderToggle: 'Enable task reminders',
    settingsAutoSyncToggle: 'Enable auto-sync flag',
    settingsDisplay: 'Display Settings',
    settingsLanguage: 'Preferred Language',
    settingsOperations: 'Operations',
    settingsManualSync: 'Trigger Manual Sync',
    saveSettings: 'Save Settings',
    saving: 'Saving...',
    syncing: 'Syncing...',

    teamAnalyticsComingSoon: 'Team Analytics Module (Coming Soon)',
    settingsComingSoon: 'System Settings Module (Coming Soon)',
  }
};

type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
